name: Reusable Deploy

on:
  workflow_call:
    secrets:
      PROD_CONNECTION_STRING:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy
        run: echo "Deploying to production"
        env:
          CONN: ${{ secrets.PROD_CONNECTION_STRING }}
