name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/reusable/build.yml
    secrets:
      DEMO_API_KEY: ${{ secrets.DEMO_API_KEY }}

  tests:
    needs: build
    uses: ./.github/workflows/reusable/tests.yml

  lint:
    needs: tests
    uses: ./.github/workflows/reusable/lint.yml

  deploy:
    needs: lint
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reusable/deploy.yml
    secrets:
      PROD_CONNECTION_STRING: ${{ secrets.PROD_CONNECTION_STRING }}
