###########################################################################################
# Disable whole body if not doing the lab in
# Stage-4-17: Deploy a Sample App to Azure Web App using GitHub Actions (non .NET version)
###########################################################################################
# name: Deploy to rajnishkumarjha (demoapps slot)
# 
# on:
#   push:
#     branches:
#       - main
# 
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
# 
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
# 
#       - name: Deploy to Azure Web App (demoapps slot)
#         uses: azure/webapps-deploy@v3
#         with:
#           app-name: rajnishkumarjha
#           slot-name: demoapps
#           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#           package: ./az400-github-app
