name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore
        working-directory: Az400.Demo.Library

      - name: Build
        run: dotnet build -c Release --no-restore
        working-directory: Az400.Demo.Library

      - name: Pack
        run: dotnet pack -c Release --no-build -o out
        working-directory: Az400.Demo.Library

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push out/*.nupkg \
            --source "github" \
            --api-key ${{ secrets.GITHUB_TOKEN }}
        working-directory: Az400.Demo.Library

# running "dotnet restore" will fail, as the .csproj file is inside Az400.Demo.Library folder
# remedies
# Option:1 Use working-directory (best)
#      - name: Restore
#        run: dotnet restore
#        working-directory: Az400.Demo.Library
# Option 2: cd inside the command (works, but less clean)
#      - name: Restore
#        run: |
#          cd Az400.Demo.Library
#          dotnet restore
# Option 3: specify path inline
#      - name: Restore
#        run: dotnet restore Az400.Demo.Library/Az400.Demo.Library.csproj
